version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/conf.d/application.conf:/etc/nginx/conf.d/application.conf
      - ~/nginx/conf.d/service-url.inc:/etc/nginx/conf.d/service-url.inc
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
  react:
    container_name: react
    image: "ghcr.io/nagyeong-park/test:latest"
    restart: always
    ports:
      - "3000:3000"
