name: CD
on:
  push:
    branches:
      - release

env:
  REPOSITORY: istock-frontend
  ORGANIZATION: pororoz

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Runner 타임존 설정
        run: |
          sudo timedatectl set-timezone 'Asia/Seoul'

      - name: Node 설정
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      # - name: Take tag version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: node_modules 폴더 캐싱
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/client/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/client/yarn.lock') }}

      - name: node_modules 폴더 캐시가 없다면 dependencies 설치
        working-directory: "./client"
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Client 소스 빌드
        working-directory: "./client"
        run: yarn build

      - name: GitHub Container Registry 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.ORGANIZATION }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Docker images build 및 GitHub Container Registry로 push
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: |
            ghcr.io/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}:latest
          # ghcr.io/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}:${{ steps.tag_version.outputs.previous_tag }}
          context: ./client

  deploy:
    needs: [push-docker-image]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ghcr.io/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}:latest
            docker run -it -d -p 3000:3000 --name react
            docker image prune
            docker logout https://ghcr.io
